### ISSUE TITLE
Android example crash when used camera

### ISSUE THREAD

**Issue by MagicalWater** [chyiiiiiiiiiiii/flutter_zendesk_messaging#21]
AndroidMainfest.xml need add follows
```
<uses-permission android:name="android.permission.CAMERA"/>
```

in messaging screen tap camera throws
```
E/AndroidRuntime(15064): Process: com.chyiiiiiiiiiiiiii.zendesk_messaging_example, PID: 15064
E/AndroidRuntime(15064): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.chyiiiiiiiiiiiiii.zendesk_messaging_example.zendesk.messaging.provider
E/AndroidRuntime(15064): 	at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:664)
E/AndroidRuntime(15064): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:695)
E/AndroidRuntime(15064): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:645)
```

**Comment by chyiiiiiiiiiiii** [comment]
Thanks. It will update in the next version.

**Comment by chyiiiiiiiiiiii** [comment]
Thank you for reporting this issue.

This issue was reported in 2023. Since then, **v3.0.0** has been released with significant SDK updates:
- Android SDK upgraded to **2.36.1**
- Improved FileProvider configuration
- Many bug fixes

Could you please try upgrading to `zendesk_messaging: ^3.0.0` and test if the camera crash is resolved?

```yaml
dependencies:
  zendesk_messaging: ^3.0.0
```

Also ensure your `AndroidManifest.xml` includes camera permission:
```xml
<uses-permission android:name="android.permission.CAMERA"/>
```

Please let us know the result. Thank you!
