### ISSUE TITLE
[ZendeskMessaging] - Login failure : HTTP 401 (No error message)

### ISSUE THREAD

**Issue by abdur-rohman** [chyiiiiiiiiiiii/flutter_zendesk_messaging#24]
Currently i am using 2.7.4 version, when i got this token and pass to login function this error occurred. I've checked the #3 and read this [reference](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/web/enabling_auth_visitors/?_ga=2.136590384.1613636631.1685927734-1503932573.1684298680), but i didn't found the solution and what i am missed from the payload. Here is the jwt format:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFwcF82NDc5OTYwOTIxNzc4NmYwOWZkeHh4eHgifQ.eyJzY29wZSI6InVzZXIiLCJuYW1lIjoiQWJkdXIgUm9obWFuIiwiZXh0ZXJuYWxfaWQiOiI0MTYxMDE1IiwiZXhwIjoxNzE3OTg2NDAwLCJpYXQiOjE2ODU5OTYxOTYsImp0aSI6IjQxNjEwMTUiLCJlbWFpbCI6Im1haWxAZ21haWwuY29tIn0.TTu_1s9hNB_fZcKyN8GUiFcTVw8w1G8sqEkKqiL0J2Y
```

![image](https://github.com/chyiiiiiiiiiiii/flutter_zendesk_messaging/assets/26162164/81d91cdf-14d7-454a-967b-61caf86c9c61)

When i was enabled the log and try to call the login with function and error occurred, there are no error message and given the error code only

```
W/AppActionProcessor( 6890): RealtimeConnectionStatusUpdate(connectionStatus=DISCONNECTED) cannot processed.
D/EffectMapper( 6890): Effect zendesk.conversationkit.android.internal.Effect$IncorrectAccessLevel@eec3b3b has no public counterpart, skipping.
E/AppActionProcessor( 6890): [UTC 2023-06-05T01:22:02Z] Failed to login
E/AppActionProcessor( 6890): retrofit2.HttpException: HTTP 401 
E/AppActionProcessor( 6890):    at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
E/AppActionProcessor( 6890):    at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
E/AppActionProcessor( 6890):    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/AppActionProcessor( 6890):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AppActionProcessor( 6890):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AppActionProcessor( 6890):    at java.lang.Thread.run(Thread.java:1012)
D/EffectMapper( 6890): Effect LoginUserResult(conversationKitSettings=zendesk.conversationkit.android.ConversationKitSettings@b0a5a79, config=Config(app=App(id=642e3277be6a38011042d2f2, status=active, name=2322021, isMultiConvoEnabled=false), baseUrl=https://ajobthing-my.zendesk.com/sc/sdk, integration=Integration(id=6433b6d72c3e28010e7b5117, canUserCreateMoreConversations=true, canUserSeeConversationList=true), restRetryPolicy=RestRetryPolicy(regular=60, aggressive=15, timeUnit=SECONDS, backoffMultiplier=2, maxRetries=5)), result=Failure(cause=retrofit2.HttpException: HTTP 401 ), clientId=5f6b489b-4ec9-4966-88d9-7d33e688a1e6) has no public counterpart, skipping.
I/System.out( 6890): [ZendeskMessaging] - Login failure : HTTP 401 
I/System.out( 6890): retrofit2.HttpException: HTTP 401
```

Thanks

**Comment by Varun9729** [comment]
@abdur-rohman were you able to login with the generated JWT?
